export const ACTIONS = {

	CONNECTION: "connection",
	CONNECTION_RESPONSE: "CONNECTION_RESPONSE",
	DISCONNECTION: "disconnect",
	
	NEW_ROOM_REQUEST: "NEW_ROOM_REQUEST",
	NEW_ROOM_RESPONSE: "NEW_ROOM_RESPONSE",
	NEW_ROOM_BROADCAST: "NEW_ROOM_BROADCAST",
	
	LEAVE_ROOM_REQUEST: "LEAVE_ROOM_REQUEST",
	LEAVE_ROOM_BROADCAST: "LEAVE_ROOM_BROADCAST",
	
	NEW_MOVE_REQUEST: "NEW_MOVE_REQUEST",
	NEW_MOVE_BROADCAST: "NEW_MOVE_BROADCAST",
	
	SINGLE_WIN_BROADCAST: "SINGLE_WIN_BROADCAST",
	ROOM_WIN_BROADCAST: "ROOM_WIN_BROADCAST",
	SINGLE_DRAW_BROADCAST: "SINGLE_DRAW_BROADCAST", 

}

export const LOG = {

	SERVER_STARTED: "SERVER_STARTED",
	SERVER_SHUTDOWN: "SERVER_SHUTDOWN",

	CONNECTION: "CONNECTION",
	CONNECTION_RESPONSE: "CONNECTION_RESPONSE",
	DISCONNECTION: "DISCONNECTION",

	USER_CREATION: "USER_CREATION",
	USER_DELETION: "USER_DELETION",
	FAILED_USER_DELETION: "FAILED_USER_DELETION", 

	ROOM_CREATION: "ROOM_CREATION",
	ROOM_DELETION: "ROOM_DELETION",
	
	NEW_ROOM_REQUEST: "NEW_ROOM_REQUEST",
	NEW_ROOM_RESPONSE: "NEW_ROOM_RESPONSE",
	NEW_ROOM_BROADCAST: "NEW_ROOM_BROADCAST",
	
	LEAVE_ROOM_REQUEST: "LEAVE_ROOM_REQUEST",
	LEAVE_ROOM_BROADCAST: "LEAVE_ROOM_BROADCAST",
	
	NEW_MOVE_REQUEST: "NEW_MOVE_REQUEST",
	NEW_MOVE_BROADCAST: "NEW_MOVE_BROADCAST",
	
	SINGLE_WIN_BROADCAST: "SINGLE_WIN_BROADCAST",
	ROOM_WIN_BROADCAST: "ROOM_WIN_BROADCAST",
	SINGLE_DRAW_BROADCAST: "SINGLE_DRAW_BROADCAST", 

	PROCESSING_PLAY_WITH_FRIEND_REQUEST: "PROCESSING_PLAY_WITH_FRIEND_REQUEST",
	FAILED_PLAY_WITH_FRIEND_REQUEST: "FAILED_PLAY_WITH_FRIEND_REQUEST",
	SUCCEEDED_PLAY_WITH_FRIEND_REQUEST: "SUCCEEDED_PLAY_WITH_FRIEND_REQUEST",

	PROCESSING_PLAY_WITH_STRANGER_REQUEST: "PROCESSING_PLAY_WITH_STRANGER_REQUEST",
	FAILED_PLAY_WITH_STRANGER_REQUEST: "FAILED_PLAY_WITH_STRANGER_REQUEST",
	SUCCEEDED_PLAY_WITH_STRANGER_REQUEST: "SUCCEEDED_PLAY_WITH_STRANGER_REQUEST",

}